// export const BASE_SERVER_URL = 'http://api.mengxun.online/gfh'
export const BASE_SERVER_URL = 'http://localhost:10310'
// export const BASE_PROXY_URL = 'http://api.mengxun.online/proxy'
export const BASE_PROXY_URL = 'http://121.5.139.173'
export const BASE_QINIU_URL = 'http://cdn-gfh.zerokirin.online'