# project config
project:
  server:
    url: 'http://localhost:xxx'
     # github page proxy
    proxy: 'http://xxx.xxx.xxx/proxy'
    # admin account
    admin: [xxx,xxx,xxx]

# mysql
mysql:
  host: 'xxx.xxx.xxx.xxx'
  port: 3306
  database: 'xxx'
  username: 'xxx'
  password: 'xxx'

github:
  # used for webspider the more the better
  tokens: [
    'xxx',
    'xxx'
  ]

# qiniu cdn config
qiniu:
  ak: 'xxx'
  sk: 'xxx'
  bucket: 'xxx'
  bucket_url: 'http://xxx'

 
  

